### PR TITLE
fix: Token state should be checked only for implicit grant type

### PR DESCRIPTION
**Pull request by deiteris**
During the manual testing, I found out that `password` and `client_credentials` grant types fail silently when attempting to request an access token via the request panel. This is due to the `/token` endpoint not including the `state` property in the response and this check seems to be only specific to the `implicit` grant type, which uses only the `/authorize` endpoint.

This check seems to be redundant, since the state is already checked during the authorization event here https://github.com/advanced-rest-client/oauth-authorization/blob/stage/src/OAuth2Authorization.js#L411, but tests are failing in this case.

### CODE REVIEW

**Review by jarrodek — APPROVED** [review]
Thank you. LGTM.

**Comment by jarrodek** [comment]
Actually, the authorization code grant type also uses authorization URI and the state parameter so both types should be included. I have to back my approval for this.

As for double checking of the state parameter. This component is built to work independently to other component. Because it uses DOM events to communicate with the application anything can handle the event and perform the authorization. The other library may not perform state checking so this redundancy is important.

**Review by jarrodek — APPROVED** [review]
I guess it's still too early for me and I need another coffee. The state parameter check in the code grant type **must** happen before the token exchange happens. Therefore it makes no sense to check it in here. I re-approve. Sorry for the confusion.

**Comment by jarrodek** [comment]
I merged with the main branch but not releasing it just yet. There's another change coming to this component I requested from my colleagues. Then it will be released.

Also @deiteris, all components are set to require signed commits. Because of this only administrators can merge the code. Would it be a trouble for you to setup a GPG signature for your commits? It's a relatively simple process. [more info](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification)

**Comment by deiteris** [comment]
> Also @deiteris, all components are set to require signed commits. Because of this only administrators can merge the code. Would it be a trouble for you to setup a GPG signature for your commits? It's a relatively simple process. [more info](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification)

Sure, I've set up a GPG signature just now.

**Pull request merged**
